### ISSUE TITLE
IrisFromCliqueCover Bug Tracking

### ISSUE THREAD

**Issue by AlexandreAmice** [AlexandreAmice/drake#80]
### What happened?

- [ ] There is an infinite loop cause by too few clique points
- [ ] We must guarantee that we sample enough points to make a big enough clique that actually adds a set.
- [ ] We need to update the plant context before calling IrisInConfigurationSpace when building an IrisRegion from a clique.
- [ ] There is a race condition when building multiple IrisRegions in parallel because they all use the same context from the collision checker.
- [ ] Sanity check the options. One user put coverage termination threshold over 1 and got the infinite loop.
